sudo: required
services:
  - docker

before_install:
  - docker build -t blindpew/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true blindpew/react-test npm test -- --coverage

after_success:
  - docker build -t blindpew/multi-client ./client
  - docker build -t blindpew/multi-nginx ./nginx
  - docker build -t blindpew/multi-server ./server
  - docker build -t blindpew/multi-worker ./worker